myplate/accounts/urls.py
from django.urls import path,include,re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_view, name="login"),
    path('logout/',views.logout_view, name="logout"),
    path('test2/',views.test2_view, name="test2"),
    path('test1/',views.test1_view, name="test1"),
    path('test3/',views.test3_view, name="test3"),
    path('dietplan/',views.dietplan_view, name="dietplan"),
    path('billgen/',views.billgen_view, name="billgen"),
    path('stock/',views.stock_view, name="stock"),
    path('render/',views.render_view, name="render"),
    path('deletion/',views.delete_view,name="delete"),
    path('survey/',views.survey_view,name="survey"),
]

myplate/myplate/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'myplate'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('accounts/',include('accounts.urls')),
]
urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myplate/accounts/models.py
from django.db import models

# Create your models here.


class Districdetails(models.Model):
    distid = models.IntegerField()
    distname = models.CharField(max_length=100)
    def __str__(self):
        return self.distid

class Studentdetails(models.Model):
    name = models.CharField(max_length=100)
    bloodgroup = models.CharField(max_length=100)
    height = models.FloatField(default=1)
    weight = models.FloatField(default=0)
    bmi = models.FloatField(default=0)
    deficency = models.TextField(default="NA")
    Schoolid = models.IntegerField(default=0)
    dob = models.DateField()
    aadhar = models.IntegerField(default=0)
    status = models.TextField(default="healthy")
    def __str__(self):
        return self.name

        
class Hmdetails(models.Model):
    hmid = models.CharField(max_length=50,default="test")
    hmname = models.CharField(max_length=50)
    school = models.CharField(max_length=50)
    address = models.TextField(max_length=100)
    schoolid = models.IntegerField(default=0,primary_key=True)
    def __str__(self):
        return self.hmid

class Billupload(models.Model):
        thumb = models.ImageField(default='default.png',blank=True)

class Menu(models.Model):
    day = models.CharField(max_length=50)
    dish1 = models.CharField(max_length=50)
    dish2 = models.CharField(max_length=50)
    dish3 = models.CharField(max_length=50)
    dish4 = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.day

myplate/accounts/forms.py
from django import forms
from . import models

class CreateArticles(forms.ModelForm):
    class Meta:
        model = models.Billupload
        fields = ['thumb']

class Menu(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ['day','dish1','dish2','dish3','dish4']

myplate/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from django.http import HttpResponse
from .models import Hmdetails,Studentdetails,Menu,Billupload
from . import forms

#renders NF page
def test1_view(request):
    return render(request,'accounts/test1.html')

#renders HM page
def test2_view(request):
    return render(request,'accounts/test2.html')

#renders HO page
def test3_view(request):
    return render(request,'accounts/test3.html')

def delete_view(request):
    Menu.objects.all().delete()
    return render(request,'accounts/rendermenu.html')

def survey_view(request):
    return render(request,'accounts/survey.html')

def render_view(request):
    menus = Menu.objects.all()
    # return HttpResponse(menu)
    menu = Menu.objects.filter()
    return render(request,'accounts/rendermenu.html',{'menus':menus})

def dietplan_view(request):
    if request.method == 'POST':
        form = forms.Menu(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('accounts:dietplan')
    else:
        form = forms.Menu() 
    menus = Menu.objects.all()
    menu = Menu.objects.filter()
    return render(request,'accounts/dietplan.html',{'form':form,'menus':menus})

def billgen_view(request):
     if request.method == 'POST':
        form = forms.CreateArticles(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('accounts:billgen')
     else:
        form = forms.CreateArticles()
     photos = Billupload.objects.all()
     photo = Billupload.objects.filter() 
     return render(request,'accounts/billgen.html',{'form':form,'photos':photos})

def stock_view(request):
    return render(request,'accounts/stock.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():     #checks if the entered values a valid and can be updated to the db
            user = form.get_user()
            #condition for head master login
            if str(form.get_user()) == 'HM':
                hmdetails = Hmdetails.objects.get(hmid=str(user))
                schooldetails = Studentdetails.objects.filter(Schoolid=str(hmdetails.schoolid))
                if str(user) == str(hmdetails):
                    login(request,user)
                    return render(request,'accounts/test2.html',{'hmdetails':hmdetails,'schooldetails':schooldetails})

            # condition for noon feeding commit login
            elif str(form.get_user()) == 'NF':
                login(request,user)
                return render(request,'accounts/test3.html')
            
            elif str(form.get_user()) == 'HO':
                login(request,user)
                return render(request,'accounts/test1.html')

    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})
    
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')




         # if str(form.get_user()) == 'HO':
            #     login(request,user)
            #     return render(request,'accounts/test2.html',{'hmdetails':hmdetails})
            # elif str(form.get_user()) == 'HM':
            #     login(request,user)
            #     return render(request,'accounts/test2.html',{'hmdetails':hmdetails})
            # elif str(form.get_user()) == 'NF':
            #     login(request,user)
            #     return render(request,'accounts/test2.html',{'hmdetails':hmdetails})
            # else:
            #     return HttpResponse('better luck next time')
            

myplate/myplate/views.py
from django.http import HttpResponse
from django.shortcuts import render



def homepage(request):
    #return HttpResponse('homepage')
    return render(request,'homelogin.html')

myplate/accounts/templates/accounts/rendermenu.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% block content %}

</style>
<a href="{%url 'accounts:test3'%}"><input type="submit" value="Back" class="btn btn-primary" style="margin-top: 1%;margin-left:90%;width: 90px;"></a>
<div style="margin-left: 20%;background-color: black;color: #ffdf01;width: 600px;border-radius: 20px;">
    <table >
        <tr>
            <td >DAY &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> 
            <td >Dish1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td>Dish2 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td>Dish3 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td>Dish4 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        </tr>
    
        {% for menu in menus%}
        <tr>
            <td>{{menu.day}}</td>
            <td>{{menu.dish1}}</td>
            <td>{{menu.dish2}}</td>
            <td>{{menu.dish3}}</td>
            <td>{{menu.dish4}}</td>
        </tr>
        {%endfor%}    
    </table>
</div>

<div class="btn1" style="padding-left: 30%;">
    <form  action="{% url 'accounts:render'%}" method="post">
        <!-- <input type="button" value="Accept"> -->
        <a href="{%url 'accounts:delete'%}"><input type="button" Value="Reject"></a>
        <a href="{%url 'accounts:render'%}"><input type="button" Value="Accept"></a>
    </form>
</div>

{%endblock%}

myplate/accounts/templates/accounts/test1.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block content %}

<!-- -----------------------------------------------
            Higher Authority Login
---------------------------------------------------->

<div class="row">
  <div class="col-3 card  shadow-sm" style="margin: 5%;padding: 3%;padding-left: 5%;">
      <h5><b>Welcome Higher Official</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 100px;width: 100px;margin-left: 10%;margin-top: 10%;"> <br>
          
              {% if user.is_authenticated %}
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning" style="margin-top: 5%;margin-left:20%">Logout</button>       
           </form>
    {% endif %}
             
  </div>
  <!--Card box for the medical report tab-->
  <div class="col-2 card  shadow-sm" style="margin-top:10%;margin-left: 2%;height: 200px;">
      <center>
          <img src="{%static 'food.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center" style="padding-top: 5%;">Diet Plan</h5>
     <center>
      <a href="{% url 'accounts:render' %}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">View Diet</button></a>
     </center>
  </div>
  <!--Card box for the Diet plan report tab-->
  
  <div class="col-2 card  shadow-sm" style="margin-top:10%;margin-left: 2%;height: 200px;">
    <center>
        <img src="{%static 'money.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
    </center>
   <h5 align="center"style="padding-top: 5%;">Billing</h5>
   <center>
     <a href="{% url 'accounts:billgen' %}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">View bill</button></a>
   </center>
</div> 
  <!--Card box for the Billing report report tab-->
  
  <div class="col-2 card  shadow-sm" style="margin-top:10%;margin-left: 2%;height: 200px;">
      <center>
          <img src="{%static 'graphic.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center"style="padding-top: 5%;">District wise stats </h5>
     <center>
       <a href="#"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">see stats</button></a>
     </center>
  </div> 
  
  
</div>

{%endblock %}

myplate/accounts/templates/accounts/test2.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block content %}

</div>
<div class="row">
  <div class="col-3 card  shadow-sm" style="padding: 2%;padding-left: 5%;margin-left: 2%;margin-top: 5%;margin-right: 2%;">
      <h5><b>Welcome Headmaster</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 100px;width: 100px;margin-left: 10%;margin-top: 10%;"> <br>
          <h5  style="padding-top: 5%;"> {{hmdetails.hmname}}</h5> 
          <h6  style="padding-top: 5%;"><b>School:</b> <br>
            {{hmdetails.school}}</h6>
          <h6><b>Address</b> <br>
            {{hmdetails.address}}</h6>
              {% if user.is_authenticated %}
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning" style="margin-top: 5%;margin-left:20%">Logout</button>       
           </form>
    {% endif %}
             
  </div>
 
    <!--Card box for the diet plan report tab-->
  <div class="col-2 card  shadow-sm" style="margin-top:13%;height: 200px;">
      <center>
          <img src="{%static 'food.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center" style="padding-top: 5%;">Diet Plan</h5>
     <center>
      <a href="{% url 'accounts:dietplan' %}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">Prepare Diet</button></a>
     </center>
  </div>
  <!--Card box for the medical report tab-->
  <div class="col-2 card  shadow-sm" style="margin-left: 1%; margin-top:13%;height: 200px;width: 100px;">
  <center>
      <img src="{%static 'health.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
  </center>
  <h5 align="center"style="padding-top: 5%;">Medical Report</h5>
  <center>
  <a href="#report"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">View Report</button></a>
  </center>
  </div>
    <!--Card box for the Stock purchase report tab-->
    <div class="col-2 card  shadow-sm" style="margin-top:13%;margin-left: 1%;height: 200px;">
      <center>
          <img src="{%static 'money.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center"style="padding-top: 5%;">Stock purchase</h5>
     <center>
       <a href="{% url 'accounts:stock' %}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">Buy Stock</button></a>
      
     </center>
  </div> 
    <!--Card box for the bill report report tab-->
  <div class="col-2 card  shadow-sm" style="margin-top:13%;margin-left: 1%;height: 200px;">
      <center>
          <img src="{%static 'money.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center"style="padding-top: 5%;">Billing</h5>
     <center>
       <a href="{% url 'accounts:billgen' %}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">Update bill</button></a>
      
     </center>
  </div> 

  
</div>
<section style="height:100v;margin-top:10%" id="report">
 <b><h2 align="center" >Students Medical Report</h2></b> 
{% for schooldetail in schooldetails%}
<div class="alert alert-primary " style="margin: 2%; ">
  <h5>{{schooldetail.name}}</h5> 
  <p><b>School Code: </b> {{schooldetail.Schoolid}} &nbsp; &nbsp; &nbsp;
  <b>Blood Group: </b> {{schooldetail.bloodgroup}}&nbsp; &nbsp; &nbsp;
  <b>DOB: </b> {{schooldetail.dob}}&nbsp; &nbsp; &nbsp;
  <b>Weight: </b> {{schooldetail.weight}}&nbsp; &nbsp; &nbsp;
  <b>Height: </b> {{schooldetail.height}}&nbsp; &nbsp; &nbsp;
  <b>BMI:</b>{{schooldetail.bmi}}&nbsp; &nbsp; &nbsp;
  <b>Status: </b>{{schooldetail.status}}
</p>
</div>
{% endfor %}
</section>
{% endblock %}
<!-- 
<h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> --><h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> --><h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> --><h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> --><h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> --><h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> --><h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> --><h1 align="center" style="padding-top: 5%;">Headmaster Login Details</h1>

<div class="card mb-4 shadow-sm" style="margin: 5%; padding: 2%;"> 
  <div class="row">
      <div class="col-4" style="padding-left: 15%;"> 
          <h5 style="margin-left: 10%;"><b>HEADMASTER</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 150px;width: 150px;margin-left: 10%;"> <br>
          {% if user.is_authenticated %}
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-warning" style="margin-left:2%;margin-top: 7%;">Logout</button>
          </form>
              </div>
      <div class="col-8" style="padding-left: 10%;">
          <h5><b>Name:</b></h5>
          <h5> {{hmdetails.hmname}}</h5> 
          <h5><b>School:</b> <br>
            {{hmdetails.school}}</h5>
          <h5><b>Address</b> <br>
            {{hmdetails.address}}

      </div>
      {% endif %}
  </div>
  

</div> -->

myplate/accounts/templates/accounts/test3.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block content %}
</div>
<!------------------------------------------------------------------------------

                                      Noon Feeding Committee Login Card
        ------------------------------------------------------------------------------ -->
<div class="row">
  <div class="col-3 card  shadow-sm" style="margin: 5%;padding: 3%;padding-left: 5%;">
      <h5><b>Welcome Noon Feeding Commitee Officer</b></h5>
          <img src="{%static 'hm.png'%}" alt="" style="height: 100px;width: 100px;margin-left: 10%;margin-top: 10%;"> <br>
              {% if user.is_authenticated %}
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning" style="margin-top: 5%;margin-left:20%">Logout</button>       
           </form>
    {% endif %}
             
  </div>
  <!------------------------------------------------------------------------------

                                      Menu Approval Card
        ------------------------------------------------------------------------------ -->
  <div class="col-2 card  shadow-sm" style="margin-top:10%;height: 200px;">
      <center>
          <img src="{%static 'test.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center"style="padding-top: 5%;">Menu Approval</h5>
     <center>
      <a href="{% url 'accounts:render' %}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">See Menu</button></a>
     </center>
  </div>
  <!------------------------------------------------------------------------------

                                      Weekly Survey Card
        ------------------------------------------------------------------------------ -->
  <div class="col-2 card  shadow-sm" style="margin-top:10%;margin-left: 2%;height: 200px;">
      <center>
          <img src="{% static 'survey.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center" style="padding-top: 5%;">Weekly Survey</h5>
     <center>
      <a href="{% url 'accounts:survey'%}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">Start Survey</button></a>
     </center>
  </div>
 <!------------------------------------------------------------------------------

                                      Medical Report Card
        ------------------------------------------------------------------------------ -->
  <!-- <div class="col-2 card  shadow-sm" style="margin-top:10%;margin-left: 2%;height: 200px;">
      <center>
          <img src="{%static 'money.png'%}" alt="" style="height: 50px;width: 50px;margin-top: 30px;">
      </center>
     <h5 align="center"style="padding-top: 5%;">Send</h5>
     <center>
       <a href="{% url 'accounts:billgen' %}"><button type="button" class="btn btn-primary" style="margin-top: 5%;width: 150px;">Upload Menu</button></a>
      
     </center>
  </div> 
</div> -->

{%endblock %}